# 路径配置
paths:
  project_root: "backend"
  agents_path: "backend/agents"
  prompts_path: "backend/agents/prompts/affirmation"
  output_path: "backend/output/affirmation"
  insight_output_path: "backend/output/affirmation/insight"
  affirmations_output_path: "backend/output/affirmation/affirmations"
  
# 提示词文件
prompts:
  insight: "backend/agents/prompts/affirmation/affiramtion_insight_prompt.txt"
  generator: "backend/agents/prompts/affirmation/affirmation_generator_promot.txt"