# 路径配置
paths:
  project_root: "backend"
  agents_path: "backend/agents"
  prompts_path: "backend/agents/prompts/chat"
  
# 提示词文件
prompts:
  chat_prompt : "backend/agents/prompts/chat/chat_prompt1.txt"
  router_prompt: "backend/agents/prompts/chat/router_prompt.txt"