# 聊天模块配置
chat:
  prompts:
    chat_prompt: "chat/chat_prompt.txt"
    router_prompt: "chat/router_prompt.txt"

# 肯定语模块配置
affirmation:
  prompts:
    insight: "affirmation/affiramtion_insight_prompt.txt"
    generator: "affirmation/affirmation_generator_promot.txt"
  output_path: "affirmation"

# 冥想模块配置
meditation:
  prompts:
    outline: "meditation/meditation_outline_promot.txt"
    script: "meditation/meditaiton_script_prompt.txt"
    tone: "meditation/meditation_tone_prompt.txt"
  output_path: "meditation"
  tts:
    tts_resources_config: "meditation/zero_shot.yaml"
    tts_output_path: "meditation/tts"