# 路径配置
paths:
  project_root: "backend"
  agents_path: "backend/agents"
  prompts_path: "backend/agents/prompts/meditation"
  output_path: "backend/output/meditation"
  outline_output_path: "backend/output/meditation/outline"
  script_output_path: "backend/output/meditation/script"
  tts_output_path: "backend/output/meditation/tts"

# TTS 配置
tts:
  tts_model_path: "/root/autodl-fs/cosyvoice/pretrained_models/CosyVoice2-0.5B"
  tts_resources_config: "backend/agents/resources/meditation/zero_shot.yaml"
  

# 提示词文件
prompts:
  outline: "backend/agents/prompts/meditation/meditation_outline_promot.txt"
  script: "backend/agents/prompts/meditation/meditaiton_script_prompt.txt"
  tone: "backend/agents/prompts/meditation/meditation_tone_prompt.txt"